Repository idea2app/Next-Bootstrap-ts, pull requests merged in 2025-05, with the labels that each got.

#52 [add] System model & Light Switch component
  .npmrc
  README.md
  components/Git/Card.tsx
  components/LanguageMenu.tsx
  components/LightSwitch.module.less
  components/LightSwitch.tsx
  components/MainNavigator.tsx
  components/NotFoundCard.tsx
  components/PageHead.tsx
  models/Base.ts
  models/System.ts
  models/Translation.ts
  models/configuration.ts
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/_error.tsx
  pages/api/core.ts
  pages/api/hello.ts
  pages/api/home.ts
  pages/article/index.tsx
  pages/component.tsx
  pages/index.tsx
  pages/pagination.tsx
  pages/scroll-list.tsx
  pnpm-lock.yaml
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement, feature

#55 fix: resolve homepage title undefined
  pages/index.tsx
Labels: bug

#56 feat: use GitHub actions cache for Docker building
  .github/workflows/deploy-production.yml
Labels: enhancement
